### ISSUE TITLE
Wondering how we can support NIP-05

### ISSUE THREAD

**Issue by redimongo** [KiPSOFT/nostr-deno-server#1]
Just wondering if it is possible to support NIP-05? by adding 5 to the server or is there code that we need to add, happy to help.

**Comment by KiPSOFT** [comment]
Hi,

NIP05 is part of the client and is not checked on the server side. When the user profile is viewed on the client, it checks the JSON file at the DNS name and compares the user profile name with the name in the JSON file. If the user name is correct, the client explains this situation.
